### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by shreyraj2002**

### CODE REVIEW

**Comment by neerajregmi10** [comment]
@shreyraj2002 Wtfff is that ??

**Comment by shreyraj2002** [comment]
Your Readme file contains so many errors so I have just rectified them

**Comment by neerajregmi10** [comment]
@shreyraj2002 Ok Thank You will see ....

**Comment by shreyraj2002** [comment]
Just merge them with your project

**Comment by shreyraj2002** [comment]
Thanks

**Pull request merged**
